Morgenmadsbuffet/Controllers/CheckInsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Morgenmadsbuffet.Data;
using Morgenmadsbuffet.Models;

namespace Morgenmadsbuffet.Controllers
{
    public class CheckInsController : Controller
    {
        private readonly ApplicationDbContext _context;

        public CheckInsController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: CheckIns
        [Authorize]
        public async Task<IActionResult> Index()
        {
            var applicationDbContext = _context.CheckIns.Include(c => c.BreakfastBookingsModels);
            return View(await applicationDbContext.ToListAsync());
        }

        // GET: CheckIns/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var checkInsModel = await _context.CheckIns
                .Include(c => c.BreakfastBookingsModels)
                .FirstOrDefaultAsync(m => m.CheckInsModelId == id);
            if (checkInsModel == null)
            {
                return NotFound();
            }

            return View(checkInsModel);
        }

        // GET: CheckIns/Create
        [Authorize("IsRestaurant")]
        public IActionResult Create()
        {
            ViewData["RoomId"] = new SelectList(_context.BreakfastBookings, "RoomId", "RoomId");
            ViewData["Date"] = new SelectList(_context.BreakfastBookings, "Date", "Date");
            return View();
        }

        // POST: CheckIns/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("CheckInsModelId,RoomId,Date,AdultCount,ChildCount")] CheckInsModel checkInsModel)
        {
            if (ModelState.IsValid)
            {
                _context.Add(checkInsModel);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["RoomId"] = new SelectList(_context.BreakfastBookings, "RoomId", checkInsModel.RoomId.ToString());
            ViewData["Date"] = new SelectList(_context.BreakfastBookings, "Date", checkInsModel.Date);
            return View(checkInsModel);
        }

        // GET: CheckIns/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var checkInsModel = await _context.CheckIns.FindAsync(id);
            if (checkInsModel == null)
            {
                return NotFound();
            }
            ViewData["RoomId"] = new SelectList(_context.CheckIns, "RoomId", checkInsModel.RoomId.ToString());
            ViewData["Date"] = new SelectList(_context.CheckIns, "Date", checkInsModel.Date);
            //ViewBag.RoomId = new SelectList(_context.BreakfastBookings, "RoomId", checkInsModel.RoomId.ToString());
            //ViewBag.Date = new SelectList(_context.BreakfastBookings, "Date", checkInsModel.Date);
            return View(checkInsModel);
        }

        // POST: CheckIns/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("CheckInsModelId,RoomId,Date,AdultCount,ChildCount")] CheckInsModel checkInsModel)
        {
            if (id != checkInsModel.CheckInsModelId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(checkInsModel);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!CheckInsModelExists(checkInsModel.CheckInsModelId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["RoomId"] = new SelectList(_context.BreakfastBookings, "RoomId", checkInsModel.RoomId.ToString());
            ViewData["Date"] = new SelectList(_context.BreakfastBookings, "Date", checkInsModel.Date);
            //ViewBag.RoomId = new SelectList(_context.BreakfastBookings, "RoomId", checkInsModel.RoomId.ToString());
            //ViewBag.Date = new SelectList(_context.BreakfastBookings, "Date", checkInsModel.Date);
            return View(checkInsModel);
        }

        // GET: CheckIns/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var checkInsModel = await _context.CheckIns
                .Include(c => c.BreakfastBookingsModels)
                .FirstOrDefaultAsync(m => m.CheckInsModelId == id);
            if (checkInsModel == null)
            {
                return NotFound();
            }

            return View(checkInsModel);
        }

        // POST: CheckIns/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var checkInsModel = await _context.CheckIns.FindAsync(id);
            _context.CheckIns.Remove(checkInsModel);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool CheckInsModelExists(int id)
        {
            return _context.CheckIns.Any(e => e.CheckInsModelId == id);
        }
    }
}

Morgenmadsbuffet/Views/CheckIns/Create.cshtml
@model Morgenmadsbuffet.Models.CheckInsModel

@{
    ViewData["Title"] = "Create";
}

<h2>Check in guests for breakfast</h2>


<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="RoomId" class="control-label"></label>
                <select asp-for="RoomId" class ="form-control" asp-items="ViewBag.RoomId"></select>
            </div>
            <div class="form-group">
                <label asp-for="Date" class="control-label"></label>
                <select asp-for="Date" class ="form-control" asp-items="ViewBag.Date"></select>
            </div>
            <div class="form-group">
                <label asp-for="AdultCount" class="control-label"></label>
                <input asp-for="AdultCount" class="form-control" />
                <span asp-validation-for="AdultCount" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ChildCount" class="control-label"></label>
                <input asp-for="ChildCount" class="form-control" />
                <span asp-validation-for="ChildCount" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Morgenmadsbuffet/Views/CheckIns/Delete.cshtml
@model Morgenmadsbuffet.Models.CheckInsModel

@{
    ViewData["Title"] = "Delete";
}

<h2>Delete</h2>

<h5>Are you sure you want to delete this?</h5>
<div>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Date)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Date)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.RoomId)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.RoomId)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.AdultCount)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.AdultCount)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.ChildCount)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.ChildCount)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="CheckInsModelId" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Morgenmadsbuffet/Views/CheckIns/Details.cshtml
@model Morgenmadsbuffet.Models.CheckInsModel

@{
    ViewData["Title"] = "Details";
}

<h2>Details on check in</h2>

<div>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Date)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Date)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.RoomId)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.RoomId)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.AdultCount)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.AdultCount)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.ChildCount)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.ChildCount)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.CheckInsModelId">Edit</a> |
    <a asp-action="Delete" asp-route-id="@Model.CheckInsModelId">Delete</a> |
    <a asp-action="Index">Back to List</a>
</div>

Morgenmadsbuffet/Views/CheckIns/Edit.cshtml
@model Morgenmadsbuffet.Models.CheckInsModel

@{
    ViewData["Title"] = "Edit";
}

<h2>Edit check in</h2>

<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="CheckInsModelId" />
            <div class="form-group">
                <label asp-for="RoomId" class="control-label"></label>
                @Html.DisplayFor(modelItem => Model.RoomId)
            </div>
            <div class="form-group">
                <label asp-for="Date" class="control-label"></label>
                @Html.DisplayFor(modelItem => Model.Date)
            </div>
            <div class="form-group">
                <label asp-for="AdultCount" class="control-label"></label>
                <input asp-for="AdultCount" class="form-control" />
                <span asp-validation-for="AdultCount" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ChildCount" class="control-label"></label>
                <input asp-for="ChildCount" class="form-control" />
                <span asp-validation-for="ChildCount" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Morgenmadsbuffet/Views/CheckIns/Index.cshtml
@using System.Security.Claims
@model IEnumerable<Morgenmadsbuffet.Models.CheckInsModel>

@{
    ViewData["Title"] = "Index";
}
<link href="~/css/site.css" rel="stylesheet" />
<h1>Check In</h1>
<p>Todays date: @DateTime.Now</p>

<form asp-controller="CheckIns">
    <button><a asp-action="Create">Check in guests for breakfast</a></button>
    <label>check in only availible for restuarant</label>
</form>
<br />
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Date)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.RoomId)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.AdultCount)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ChildCount)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Date)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.RoomId)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.AdultCount)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.ChildCount)
                </td>
                <td>
                    <a asp-action="Details" asp-route-id="@item.CheckInsModelId">Details</a>
                </td>
            </tr>
        }
    </tbody>
</table>